### ISSUE TITLE
Replace deprecated JQuery functions and event shorthands

### ISSUE THREAD

**Issue by anikitas** [morriznet/jquery.readall#1]
Hello,

Just testing the library.
The script is works find well done!
Just found some JQuery migrate warnings, and i though i could share. 

Just need to replace two instances.

One click

from:
`.click(function (e) {`
to:
`.on( 'click',function (e) {`

and the bind in orientation:

from:
`$(window).bind('orientationchange resize', onResize);`
to:
`$(window).on('orientationchange resize', onResize);`

I hope it helps!

Happy to create a pull request too.

**Comment by morriznet** [comment]
Sorry for the late reply.
Thankyou for your input. I have updated the repo and released a new version.
Please tell me if you find anything else, or flle free to make a pull request.
