### ISSUE TITLE
What's the sense of $this.parent().not(wrapperclass) ?

### ISSUE THREAD

**Issue by Hibrix-net** [morriznet/jquery.readall#2]
Hello,

I don't understand why you do this check here in line 54:
`if ($this.parent().not(wrapperclass)) {`

You're using ".not()": https://api.jquery.com/not/

What's the sense of this line of code?

Kind regards,

**Comment by morriznet** [comment]
This is just a safetycheck to make sure that the class is ok.

**Comment by Hibrix-net** [comment]
> This is just a safetycheck to make sure that the class is ok.

Thanks, but Isn't a bit redundant? You have to construct the wrapper anyway after it right?

**Comment by morriznet** [comment]
Yes, but if the same class has been used then it will become wrong. For that reason this check is made to make sure it is a correct implementation.

**Comment by Hibrix-net** [comment]
> Yes, but if the same class has been used then it will become wrong. For that reason this check is made to make sure it is a correct implementation.

Sorry to insist, but I still believe there's an error: You're using the `not()` method that is always returning an object, so on one hand this will always be `true`. For using it in a conditional check you must add `length`
E.g.:  `if ($this.parent().not(wrapperclass)).length`

And on the other hand you declared `wrapperclass = 'readall-wrapper'`
And this will become: `$this.parent().not('readall-wrapper')`
It's missing the dot there to be a valid selector expression for the class `.readall-wrapper`
So you must do: `$this.parent().not('.readall-wrapper').length` instead, to make it work as you wanted.

Am I right or am I missing something here?
